version: '3.1'
services:
  APP:
    image: 'IMAGE_NAME_LOCAL_OR_FROM_DOCKERHUB>'
    ports:
      - "8080:8080"
    depends_on:
      [PostgreSQL]
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/<DB-NAME>
      - SPRING_DATASOURCE_USERNAME=<USERNAME>
      - SPRING_DATASOURCE_PASSWORD=<PASSWORD>
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=<PASSWORD>
      - POSTGRES_USER=<USERNAME>
      - POSTGRES_DB=<DB_NAME>
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5